In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [ ]:
a = np.array([1,2,'aa','bb',34,35])

In [ ]:
print(a.dtype)
print(a)

<U21
['1' '2' 'aa' 'bb' '34' '35']

In [ ]:
s= pd.Series(a, index = list(range(10,16)))
s

10     1
11     2
12    aa
13    bb
14    34
15    35
dtype: object

In [ ]:
lt = [1,2,'aa','bb',34,35]

In [ ]:
type(lt)

list

In [ ]:
mydic = {'Snake':0,'Birds':2,'Cat':4, 'Human':2}

In [ ]:
myD = pd.Series(mydic)
myD

Snake    0
Birds    2
Cat      4
Human    2
dtype: int64

In [ ]:
myD['Birds']

np.int64(2)

In [ ]:
s= pd.Series(100, index = list(range(5,10)))

In [ ]:
df= pd.read_csv('/German-Credit_1.xls')

In [ ]:
df.head()

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
0,1,6.0,0.0,0.0,0.0,1.0,0.0,0.0,1169.0,4.0,...,0.0,67.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,1.0
1,2,48.0,0.0,0.0,0.0,1.0,0.0,0.0,5951.0,2.0,...,0.0,22.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
2,3,12.0,0.0,0.0,0.0,0.0,1.0,0.0,2096.0,2.0,...,0.0,49.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,0.0,45.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0
4,5,24.0,1.0,0.0,0.0,0.0,0.0,0.0,4870.0,3.0,...,1.0,53.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0

In [ ]:
df.tail(3)

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
997,998,12.0,0.0,0.0,0.0,1.0,0.0,0.0,804.0,4.0,...,0.0,38.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
998,999,45.0,0.0,0.0,0.0,1.0,0.0,0.0,1845.0,4.0,...,1.0,23.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
999,1000,45.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,3.0,...,0.0,NaN,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0

In [ ]:
df.shape

(1000, 23)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBS             1000 non-null   int64
 1   DURATION        998 non-null    float64
 2   NEW_CAR         999 non-null    float64
 3   USED_CAR        999 non-null    float64
 4   FURNITURE       999 non-null    float64
 5   RADIO_TV        997 non-null    float64
 6   EDUCATION       996 non-null    float64
 7   RETRAINING      996 non-null    float64
 8   AMOUNT          990 non-null    float64
 9   INSTALL_RATE    993 non-null    float64
 10  CO_APPLICANT    992 non-null    float64
 11  GUARANTOR       993 non-null    float64
 12  REAL_ESTATE     993 non-null    float64
 13  PROP_UNKN_NONE  993 non-null    float64
 14  AGE             990 non-null    float64
 15  OTHER_INSTALL   991 non-null    float64
 16  RENT            992 non-null    float64
 17  OWN_RES         993 non-null    float64
 18  NUM_CREDITS     994 non-null    float64
 19  NUM_DEPENDENTS  993 non-null    float64
 20  TELEPHONE       995 non-null    float64
 21  FOREIGN         994 non-null    float64
 22  RESPONSE        997 non-null    float64
dtypes: float64(22), int64(1)
memory usage: 179.8 KB

In [ ]:
df_sub = df['EDUCATION']
df_sub.head()

0    0.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: EDUCATION, dtype: float64

In [ ]:
df.std()

OBS                288.819436
DURATION            12.064656
NEW_CAR              0.423731
USED_CAR             0.304246
FURNITURE            0.384530
RADIO_TV             0.449146
EDUCATION            0.218469
RETRAINING           0.296636
AMOUNT            2826.183525
INSTALL_RATE         1.119055
CO_APPLICANT         0.199154
GUARANTOR            0.222877
REAL_ESTATE          0.450187
PROP_UNKN_NONE       0.362169
AGE                 11.342694
OTHER_INSTALL        0.389851
RENT                 0.383065
OWN_RES              0.452118
NUM_CREDITS          0.576302
NUM_DEPENDENTS       0.363126
TELEPHONE            0.490750
FOREIGN              0.189404
RESPONSE             0.458444
dtype: float64

In [ ]:
df.describe()

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
count,1000.000000,998.000000,999.000000,999.000000,999.00000,997.000000,996.000000,996.000000,990.000000,993.000000,...,993.000000,990.000000,991.000000,992.000000,993.000000,994.000000,993.000000,995.000000,994.000000,997.000000
mean,500.500000,20.917836,0.234234,0.103103,0.18018,0.279840,0.050201,0.097390,3273.168687,2.972810,...,0.155086,35.505051,0.186680,0.178427,0.713998,1.406439,1.156093,0.403015,0.037223,0.700100
std,288.819436,12.064656,0.423731,0.304246,0.38453,0.449146,0.218469,0.296636,2826.183525,1.119055,...,0.362169,11.342694,0.389851,0.383065,0.452118,0.576302,0.363126,0.490750,0.189404,0.458444
min,1.000000,4.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,250.000000,1.000000,...,0.000000,19.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,250.750000,12.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1371.250000,2.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
50%,500.500000,18.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2321.500000,3.000000,...,0.000000,33.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,750.250000,24.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,3970.500000,4.000000,...,0.000000,42.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,0.000000,1.000000
max,1000.000000,72.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,18424.000000,4.000000,...,1.000000,75.000000,1.000000,1.000000,1.000000,4.000000,2.000000,1.000000,1.000000,1.000000

In [ ]:
df.describe(include = 'all')

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
count,1000.000000,998.000000,999.000000,999.000000,999.00000,997.000000,996.000000,996.000000,990.000000,993.000000,...,993.000000,990.000000,991.000000,992.000000,993.000000,994.000000,993.000000,995.000000,994.000000,997.000000
mean,500.500000,20.917836,0.234234,0.103103,0.18018,0.279840,0.050201,0.097390,3273.168687,2.972810,...,0.155086,35.505051,0.186680,0.178427,0.713998,1.406439,1.156093,0.403015,0.037223,0.700100
std,288.819436,12.064656,0.423731,0.304246,0.38453,0.449146,0.218469,0.296636,2826.183525,1.119055,...,0.362169,11.342694,0.389851,0.383065,0.452118,0.576302,0.363126,0.490750,0.189404,0.458444
min,1.000000,4.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,250.000000,1.000000,...,0.000000,19.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,250.750000,12.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1371.250000,2.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
50%,500.500000,18.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2321.500000,3.000000,...,0.000000,33.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,750.250000,24.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,3970.500000,4.000000,...,0.000000,42.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,0.000000,1.000000
max,1000.000000,72.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,18424.000000,4.000000,...,1.000000,75.000000,1.000000,1.000000,1.000000,4.000000,2.000000,1.000000,1.000000,1.000000

In [ ]:
df.loc[1:5,'NEW_CAR':'RETRAINING']

   NEW_CAR  USED_CAR  FURNITURE  RADIO_TV  EDUCATION  RETRAINING
1      0.0       0.0        0.0       1.0        0.0         0.0
2      0.0       0.0        0.0       0.0        1.0         0.0
3      0.0       0.0        1.0       0.0        0.0         0.0
4      1.0       0.0        0.0       0.0        0.0         0.0
5      0.0       0.0        0.0       0.0        1.0         0.0

In [ ]:
df.iloc[1:5,2:8]

   NEW_CAR  USED_CAR  FURNITURE  RADIO_TV  EDUCATION  RETRAINING
1      0.0       0.0        0.0       1.0        0.0         0.0
2      0.0       0.0        0.0       0.0        1.0         0.0
3      0.0       0.0        1.0       0.0        0.0         0.0
4      1.0       0.0        0.0       0.0        0.0         0.0

In [ ]:
mean_AMOUNT = df['AMOUNT'].mean()
print(mean_AMOUNT)

3273.168686868687